login_project/login_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('', include('django.contrib.auth.urls')),
]

login_project/main_app/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .forms import LoginForm
from django.contrib.auth import views as authv

urlpatterns = [
    # index
    path(r'', views.index, name='index'),
    # profile
    path(r'user_profile/', views.profile, name='profile'),
    # register
    path(r'user_register/', views.register, name='register'),
    path(r'user_register_save/', views.register_save, name='register_save'),
    # login
    path(r'user_login/', authv.LoginView.as_view(template_name='main_app/login.html',
                                                 authentication_form=LoginForm), name='login'),
    # logout
    path(r'user_logout/', authv.LogoutView.as_view(template_name='main_app/logout.html'), name='logout'),
    # password reset
    path(r'user_login/password_reset/', views.password_reset, name='password_reset'),
    path(r'user_login/password_reset_done/', views.password_reset_done, name='password_reset_done'),
    # password reset confirm using url method (I can't build using path method.. why?)
    url(
        r'^user_login/password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    path(r'user_login/password_reset_complete', views.password_reset_complete, name='password_reset_complete'),
    # end password

    # project
    url(r'^user_profile/project/(?P<project_name>[0-9A-Za-z_\-]+)/action', views.handle_select_button, name='handle_button'),
    url(r'^user_profile/project/(?P<project_name>[0-9A-Za-z_\-]+)/upload_complete', views.form, name='uploading'),
    url(r'^user_profile/project/(?P<project_name>[0-9A-Za-z_\-]+)/', views.certain_project, name='your_project'),
]

app_name = 'main_app'

login_project/main_app/models.py
from django.db import models
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from datetime import datetime

# Create your models here.


class FileUpModel(models.Model):
    file_name = models.CharField(max_length=100)
    upload_time = models.DateTimeField(default=datetime.now)
    upload_size = models.FloatField(default=0)
    upload_path = models.CharField(max_length=100, default='/')
    upload_group = models.CharField(max_length=50, default="")

login_project/main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.core.mail import EmailMultiAlternatives
from django.template import loader


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = (
            "username", "email", "password1", "password2",
            "first_name", "last_name",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザネーム'

        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = '姓'

        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = '名'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = '確認用パスワード'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Eメールアドレス'

    # メールアドレスの重複を確認する
    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("このメールアドレスは使用済みです")
        return data


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザネーム'

        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワード'

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'], code='inactive', )
        if user.is_active:
            messages.add_message(self.request, messages.SUCCESS, user.username + "のログインに成功しました")


class ForgetPasswordForm(PasswordResetForm):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        # Email subject *must not* contain newlines
        subject = "djangoからのお知らせ"
        body = loader.render_to_string('main_app/password_reset_subject.txt', context)

        email_message = EmailMultiAlternatives(subject, body, 'django@ushi.com', [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()


class PasswordConfirmForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['placeholder'] = '新パスワード'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['placeholder'] = '新パスワード（確認）'


class UploadFileForm(forms.Form):
    file = forms.FileField()

login_project/main_app/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, HttpResponse, Http404
from django.views.decorators.http import require_POST
from django.urls import reverse_lazy
from .forms import RegisterForm, PasswordConfirmForm, ForgetPasswordForm, UploadFileForm
from django.contrib import messages
from django.contrib.auth import views as authv
from django import template
from .models import FileUpModel
from .utils import group, file_upload
import os, sys, re
from datetime import datetime
from urllib.parse import quote
from unidecode import unidecode


def index(request):
    context = {
        'user': request.user,
    }
    return render(request, 'main_app/index.html', context)


register = template.Library()


def profile(request):
    context = {
        'user': request.user,
        'group_flag': group.has_group_bool(request),
        'group_list': group.get_user_group_list(request)
    }
    return render(request, 'main_app/profile.html', context)


def register(request):
    form = RegisterForm(request.POST or None)
    context = {
        'form': form,
    }
    return render(request, 'main_app/register.html', context)


@require_POST
def register_save(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "ユーザが正しく登録されました")
            return redirect('main_app:register')
    else:
        form = RegisterForm()

    context = {
        'form': form,
    }
    return render(request, 'main_app/register.html', context)


def password_reset(request):
    context = {
        'post_reset_redirect': reverse_lazy('main_app:password_reset_done'),
        'template_name': 'main_app/password_reset.html',
        'password_reset_form': ForgetPasswordForm,
    }
    return authv.password_reset(request, **context)


def password_reset_done(request):
    context = {
        'template_name': 'main_app/password_reset_done.html'
    }
    return authv.password_reset_done(request, **context)


def password_reset_confirm(request, uidb64, token):
    context = {
        'uidb64': uidb64,
        'token': token,
        'post_reset_redirect': reverse_lazy('main_app:password_reset_complete'),
        'template_name': 'main_app/password_reset_confirm.html',
        'set_password_form': PasswordConfirmForm,
    }
    return authv.password_reset_confirm(request, **context)


def password_reset_complete(request):
    context = {
        'template_name': 'main_app/password_reset_complete.html',
    }
    return authv.password_reset_complete(request, **context)


def certain_project(request, project_name):
    illegal_direct_flag = False
    print(group.get_user_group_list(request))
    print(project_name)
    for gs in group.get_user_group_list(request):
        if str(gs) == project_name:
            illegal_direct_flag = True
            break

    if illegal_direct_flag:
        query_sets = select_records_in_group(project_name)
        context = {
            'user': request.user,
            'group_flag': group.has_group_bool(request),
            'group_list': group.get_user_group_list(request),
            'send_to_html_project': project_name,
            'query_sets': query_sets,
        }
        return render(request, 'main_app/profile_introduce.html', context)
    else:
        return redirect('main_app:profile')



# uploader

UPLOAD_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/'


def form(request, project_name):
    # アップロードに失敗した場合でもデータを表示するために必要
    query_sets = select_records_in_group(project_name)

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            file_size = file.size
            upload_directory = os.path.join(UPLOAD_DIR, 'files/' + str(project_name))
            path = upload_directory + '/' + file.name
            os.makedirs(upload_directory, exist_ok=True)
            print(upload_directory)

            file_upload.handle_uploaded_file(file, path)

            # DB
            insert_data = FileUpModel(file_name=file.name, upload_time=datetime.now(), upload_size=file_size,
                                      upload_path=path, upload_group=project_name)
            insert_data.save()
            key_value_upload = 1

            # アップロードに成功させた後にデータを即時反映させるために必要
            query_sets = select_records_in_group(project_name)

            context = {
                'user': request.user,
                'file_name': file.name,
                'file_size': file_size,
                'group_flag': group.has_group_bool(request),
                'group_list': group.get_user_group_list(request),
                'send_to_html_project': project_name,
                'key_value_upload': key_value_upload,
                'query_sets': query_sets,
            }
            return render(request, 'main_app/profile_introduce.html', context)

        else:
            key_value_upload = -1
            print("flag" + str(key_value_upload))
            context = {
                'user': request.user,
                'group_flag': group.has_group_bool(request),
                'group_list': group.get_user_group_list(request),
                'send_to_html_project': project_name,
                'key_value_upload': key_value_upload,
                'query_sets': query_sets,
            }
            return render(request, 'main_app/profile_introduce.html', context)


def upload_complete(request):
    return render(request, 'main_app/upload_complete.html')


def handle_select_button(request, project_name):
    print(request.POST)
    if request.method == 'POST':
        if 'download_button' in request.POST:
            return download_file(request, project_name)
        elif 'delete_button' in request.POST:
            delete_file(request, project_name)
        query_sets = select_records_in_group(project_name)
        context = {
            'user': request.user,
            'group_flag': group.has_group_bool(request),
            'group_list': group.get_user_group_list(request),
            'send_to_html_project': project_name,
            'query_sets': query_sets,
        }
        return render(request, 'main_app/profile_introduce.html', context)


def download_file(request, project_name):
    file_name = request.POST['download_button']
    path = select_path_in_group_and_title(project_name, file_name)
    if os.path.exists(path):
        with open(path, 'rb') as f:
            print(f)
            response = HttpResponse(f.read(), content_type='application/octet-stream')
            response['Content-Disposition'] = \
                "attachment;" \
                "filename={ascii_filename};" \
                "filename*=UTF-8''{utf_filename}".format(
                    ascii_filename=unidecode(file_name).replace(' ', '_'),
                    utf_filename=quote(file_name)
                )
            return response
        raise Http404


def delete_file(request, project_name):
    # fileの削除
    file_name = request.POST['delete_button']
    path = select_path_in_group_and_title(project_name, file_name)
    # DBからデータを削除 (同じ名前/パスのものは一括削除)
    delete_path_in_group_and_title(project_name, file_name, path)
    os.remove(path)




# DB statements as follows:
# equal to "select file_name, upload_path, upload_size, upload_time from tbl where upload_group=group_str
# order by upload_time"
def select_records_in_group(group_str):
    query = FileUpModel.objects.values_list('file_name', 'upload_path', 'upload_size', 'upload_time').filter(
        upload_group=group_str).distinct().order_by('upload_time').reverse()
    query_sets = [q for q in query]
    return query_sets


def select_path_in_group_and_title(group_str, title_str):
    query = FileUpModel.objects.values_list('upload_path').filter(upload_group=group_str) \
        .filter(file_name=title_str).distinct().order_by('upload_time').reverse().first()
    return query[0]


def delete_path_in_group_and_title(group_str, title_str, path_str):
    FileUpModel.objects.all().filter(upload_group=group_str) \
        .filter(file_name=title_str).filter(upload_path=path_str).delete()

login_project/main_app/templates/main_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <title>アプリ配信サイト</title>

    <!-- Bootstrap core CSS -->
    <link href='{% static "bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href='{% static "bootstrap/css/ie10-viewport-bug-workaround.css" %}' rel="stylesheet">

    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <link href='{% static "bootstrap/css/custom_css/custom.css" %}' rel="stylesheet">

</head>
<body>
<!-- Added navbar by Bootswatch. Theme: Jet black and electric blue (https://bootswatch.com/cyborg/) -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="">アプリ配信サイト</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% ifequal request.path '/' %}active{% endifequal %}">
                    <a class="nav-link" href="{% url 'main_app:index' %}">Home</a>
                </li>
                <li class="nav-item {% ifequal request.path '/user_profile/' %}active{% endifequal %}">
                    <a class="nav-link" href="{% url 'main_app:profile' %}">Profile</a>
                </li>
                <!-- if user is logged in, show logout tab instead of login tab-->
                {% if user.is_authenticated %}
                <li class="nav-item {% ifequal request.path '/user_logout/' %}active{% endifequal %}">
                    <a class="nav-link" href="{% url 'main_app:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item {% ifequal request.path '/user_login/' %}active{% endifequal %}">
                    <a class="nav-link" href="{% url 'main_app:login' %}">Login</a>
                </li>
                {% endif %}
                <li class="nav-item {% ifequal request.path '/user_register/' %}active{% endifequal %}">
                    <a class="nav-link" href="{% url 'main_app:register' %}">Register</a>
                </li>
            </ul>
        </div>
        <a class="navbar-brand" style="color:#fff">
            {% if user.is_authenticated %}
            ようこそ {{ user.username }}
            {% endif %}
        </a>
    </div>
</nav>

<!-- main content -->
<div class="content">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>

<!-- footer: Footer was only set for id so that "footerFixed.js" related to fix position under is needed to use id-->
<div id="footer">
    <div class="container">
        <div class="col-lg-12" style="padding-top: 20px; color:#fff;">
            <p>Made by <a href="mailto:sh-ushikubo@kddi.com">Sho Ushikubo</a>.</p>
            <p>Code released under the <a href="https://github.com/thomaspark/bootswatch/blob/master/LICENSE">MIT
                License</a>.</p>
            <p>Based on <a href="https://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a
                    href="http://fontawesome.io/" rel="nofollow">Font Awesome</a>. Web fonts from <a
                    href="https://fonts.google.com/" rel="nofollow">Google</a>.</p>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- footer fixing under -->
<script type="text/javascript" src="{% static 'bootstrap/js/custom_js/footerFixed.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</body>
</html>

login_project/main_app/templates/main_app/index.html
{% extends "main_app/base.html" %}
{% block content %}
<!-- if u logged in, show pop-up of success message-->
{% if messages %}
{%for message in messages %}
<div class="alert alert-dismissible alert-primary">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>{{ message }}</strong>
</div>
{% endfor %}
{% endif %}

<h2>アプリ配信サイトの説明</h2>
<hr class="my-4">
<p class="lead">Home: トップ画面です</p>
<hr class="my-4">
<p class="lead">Profile: ログイン後、確認可能な画面です</p>
<hr class="my-4">
<p class="lead">Login: ログイン画面です</p>
<hr class="my-4">
<p class="lead">Register: ユーザ登録画面です</p>
{% endblock %}

login_project/main_app/templates/main_app/loaded_form.html
{% load widget_tweaks %}

{% for field in form %}
<div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
    {% if field.errors %}
    {% render_field field class="form-control is-invalid" %}
    {% for error in field.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
    {% endfor %}
    {% else %}
    {% render_field field class="form-control is-valid" %}
    {% endif %}
    {% else %}
    {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
    <small class="form-text text-muted">
        {{ field.help_text }}
    </small>
    {% endif %}
</div>
{% endfor %}

login_project/main_app/templates/main_app/login.html
{% extends "main_app/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
            {% endfor %}
            <div class="panel-heading">
                <h3 class="panel-title">ログイン</h3>
            </div>
            <div class="panel-body">
                <form class="my-form" action="{% url 'main_app:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.username }}
                        {{ form.username.errors }}
                    </div>

                    <div class="form-group">
                        {{ form.password }}
                        {{ form.password.errors }}
                    </div>

                    <input type="submit" class="btn btn-success btn-lg btn-block" value="ログイン">
                    <input type="hidden" name="next" value={{ request.username }}/>
                </form>
                <div align="right" style="margin-top:20px;">
                    <a href="password_reset">パスワードを忘れた方はこちら</a>
                    <img src="{% static 'img/angle-right.svg' %}" width="24" height="24" align="right">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

login_project/main_app/templates/main_app/logout.html
{% extends "main_app/base.html" %}
{% block content %}
<h3>ログアウトが完了しました</h3>
{% endblock %}

login_project/main_app/templates/main_app/password_reset.html
{% extends "main_app/base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">パスワードリセット</h3>
                <div class="panel-body">
                    <p>アカウント登録したメールアドレスを記載して下さい</p>
                    <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% include 'main_app/loaded_form.html' %}
                        <button type="submit" class="btn btn-success btn-lg btn-block">パスワードをリセットするメールを送信</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

login_project/main_app/templates/main_app/password_reset_complete.html
{% extends "main_app/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>パスワードリセットページ</h1>
    <p class="lead">パスワードをリセットしました。</p>
  </div>
</div><!-- /.container -->
{% endblock %}

login_project/main_app/templates/main_app/password_reset_confirm.html
{% extends "main_app/base.html" %}
{% block content %}
<div class="container">
    <div class="center">
        <h1>パスワードリセットページ</h1>
        <p class="lead">新パスワードを入力してください</p>
    </div>
    <form action="" method="POST">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="form-group">
                            {{ form.new_password1 }}
                            {{ form.new_password1.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.new_password2 }}
                            {{ form.new_password2.errors }}
                        </div>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-lg btn-block">送信</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div><!-- /.container -->
{% endblock %}

login_project/main_app/templates/main_app/profile.html
{% extends "main_app/base.html" %}
{% block content %}
{% if group_flag and user.is_authenticated %}

<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-12 col-md-9">
        {% ifequal request.path '/user_profile/' %}
        右のプロジェクト欄から選択して下さい
        {% endifequal %}
        {% block profile_content %}
        {% endblock %}
    </div><!--/span-->

    <div class="col-6 col-md-3 sidebar-offcanvas" id="sidebar">
        <ul class="list-group">
            {% for group in group_list %}
            <a href="/user_profile/project/{{group}}/" class="list-group-item active" style="margin-bottom:2px;">
                {{group}}</a>
            {% endfor %}
        </ul>
    </div><!--/span-->
</div><!--/row-->

{% else %}
<div class="container">
    <p class="lead">ログイン後確認可能です</p>
    <p class="lead">下のボタンを押してログインして下さい</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'main_app:login' %}" role="button">ログイン</a>
    </p>
</div>
{% endif %}

{% endblock %}

login_project/main_app/templates/main_app/profile_introduce.html
{% extends "main_app/profile.html"%}
{% load staticfiles %}

{% block profile_content %}
<br>
パス名 from profile_introduce.html :{{ request.path }}
<br>
受け渡したプロジェクト名: {{ send_to_html_project }}

{% ifequal key_value_upload 1 %}
<div class="alert alert-dismissible alert-primary">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    アップロードに成功しました
</div>
{% endifequal %}
{% ifequal key_value_upload -1 %}
<div class="alert alert-dismissible alert-primary">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    アップロードに失敗しました
</div>
{% endifequal %}

<h4>アップロードフォーム</h4>
<br>
<form action="{% url 'main_app:uploading' send_to_html_project %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <input type="submit" class="btn btn-primary btn-rounded btn-sm my-0" value="アップロード">
</form>
<hr>
{% include 'main_app/show_db_record.html' %}

{% endblock%}

login_project/main_app/templates/main_app/register.html
{% extends "main_app/base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            {% if messages %}
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
            {% endif %}
            <div class="panel-heading">
                <h3 class="panel-title">ユーザ登録</h3>
            </div>
            <div class="panel-body">

                <form action="{% url 'main_app:register_save' %}" method="POST">

                    <div class="form-group">
                        {{ form.username }}
                        {{ form.username.errors }}
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                {{ form.password1 }}
                                {{ form.password1.errors }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                {{ form.password2 }}
                                {{ form.password2.errors }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                {{ form.first_name }}
                                {{ form.first_name.errors }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="form-group">
                                {{ form.last_name }}
                                {{ form.last_name.errors }}
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        {{ form.email }}
                        {{ form.email.errors }}
                    </div>

                    <input type="submit" class="btn btn-success btn-lg btn-block" value="登録">
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

login_project/main_app/templates/main_app/show_db_record.html
{% load staticfiles %}
<head>
    <link href='{% static "bootstrap/css/custom_css/uploaded_table.css" %}' rel="stylesheet">
</head>

<body>
<div class="uploader_to_query">
    <h4>アップロード済みデータ一覧</h4>
    <table class="table table-bordered table-hover">
        <!--Table head-->
        <thread>
            <tr class="table-active">
                <th>タイトル</th>
                <th class="">サイズ [byte]</th>
                <th class="">更新日時</th>
                <th class="">ダウンロード</th>
                {% if user.is_staff %}
                <th class="">削除</th>
                {% endif %}
            </tr>
        </thread>

        <tbody>
        {% for title, path, size, time in query_sets %}
        <tr>
            <td>{{ title }}</td>
            <td>{{ size }}</td>
            <td>{{ time }}</td>
            <form action="{% url 'main_app:handle_button' send_to_html_project %}" method="POST"
                  enctype="application/x-www-form-urlencoded">
                {% csrf_token %}
                <td>
                    <input type="submit" class="btn btn-primary btn-rounded btn-sm my-0" value="ダウンロード">
                    <input type="hidden" name="download_button" value="{{title}}">
                </td>
            </form>
            {% if user.is_staff %}
            <form action="{% url 'main_app:handle_button' send_to_html_project %}" method="POST"
                  enctype="application/x-www-form-urlencoded">
                {% csrf_token %}
                <td>
                    <input type="submit" class="btn btn-primary btn-rounded btn-sm my-0" value="削除">
                    <input type="hidden" name="delete_button" value="{{title}}">
                </td>
            </form>
            {% endif %}
        </tr>
        </tbody>
        {% empty %}
        <div class="alert alert-dismissible alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p>ファイルがアップロードされていません</p>
        </div>
        {% endfor %}
    </table>
</div>
</body>

login_project/main_app/templates/main_app/upload_complete.html
{% extends "main_app/profile_introduce.html"%}

{% block profile_content %}
<br>
パス名 from profile_introduce.html :{{ request.path }}
<br>
受け渡したプロジェクト名: {{ send_to_html_project }}
<form action="{% url 'main_app:uploading' send_to_html_project %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <input type="submit" value="アップロード">
</form>


{% endblock%}